### ISSUE TITLE
Testing: Persistent Identifiers Module

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka-s-modules/PersistentIdentifiers#4]
This module will allow users to create or import persistent identifiers (PIDs) & assign them to Omeka S items. These PIDs can be either assigned at item creation or assigned or removed later via the item edit or batch edit screens. PIDs may also be "extracted" from existing metadata fields. Once assigned, accessing an item's PID in browser should resolve to a stable, non-site-specific landing page containing the items metadata, media & any sites the item is assigned to.

As there are more than a few existing services for PID "minting" (generation) and management, the module is designed to be flexible enough to allow for multiple PID services to be used (though only one PID service may be used at a time to mint and assign PIDs to items). Most PID services will mint and manage only a certain type of PID. The current PID services for testing and initial release are:

- EZID (used to mint and manage ARKs)
- DataCite (used to mint and manage DOIs)

# General Settings

After installation, _Persistent Identifiers_ should appear in the left nav bar under **Modules**. The _Settings_ subpage features general settings:

**PID Service**: Select which of the available PID services to use for minting/extraction.

**Assign PID to New Items**: Check this box to automatically either newly mint or extract an existing PID (see "Fields with Existing PIDs" below) and assign to every new item in Omeka S, whether created from within the Omeka S interface or imported from another Omeka/Dspace/etc. instance using another module.

**Fields with Existing PIDs**: A list of metadata fields, separated by commas, that may contain PID values within a newly created or imported item. If found, the existing PID will be assigned to the item instead of a new PID being minted.

# EZID Configuration

**NAAN & Shoulder Namespace**: The Name Assigning Authority Number (NAAN) and ARK shoulder value uniquely assigned to an organization, which will appear in every ARK generated. _For testing purposes, use:_ ark:/99999/fk4

**EZID Username**: the EZID user with permission to create and update identifiers for the above namespace. _For testing purposes, use:_ apitest

**EZID Password**: password for the above EZID user. Note that this password does not "save", so if changes are made to the NAAN or Username, you must also re-enter the password before pressing "submit" _For testing purposes, use:_ apitest

# DataCite Configuration

**Repository DOI Prefix**: The prefix assigned to an institution's DOI minting and management repository, which will appear in every DOI generated. _For testing purposes, use:_ 10.82157

**DataCite Repository ID**: the unique identifier assigned to an institution's DOI repository. _For testing purposes, use:_ XQZU.RBBDXB

**DataCite Password**: password associated with the above DataCite Repository ID. Note that this password does not "save", so if changes are made to any field on the DataCite Configuration screen, you must also re-enter the password before pressing "submit" _For testing purposes, use:_ murgatroid

**DataCite Required Metadata**
DataCite requires five descriptive metadata values in order to generate a DOI: Title, Creators, Publisher, Publication Year, and Resource Type. All of these fields must be mapped to an existing metadata field, selected from the list of available metadata vocabularies in your Omeka S instance.

# Testing Tasks

_For each service_

After inputting credentials:
- Mint a PID from item edit page: Click on an item, click "Edit Item" and navigate to the _Advanced_ tab. click **Mint PID** and wait a few moments and the ARK or DOI should appear, with the button now changing to **Remove PID**
- After pressing "Save" on the item, ensure _Persistent Identifier_ and appropriate value appears in the right nav metadata below "Owner"
- Remove a PID from item edit page: From the "Edit Item" page _Advanced_ tab, click the  **Remove PID** button. A dialogue will pop up warning you that this will remove the PID and break any incoming links. Ensure both the PID and item ID appear in this window. Click **Confirm Remove PID** and ensure that the PID disappears from the _Advanced_ tab, the button changes back to **Mint PID** and upon pressing "Save", _Persistent Identifier_ and value no longer appear in the right nav metadata.
- Assign PIDs to all new items: Check **Assign PIDs to new items** on the PID module **Settings** page. Create a new item within Omeka S interface and ensure that a PID value appears in the item's right nav metadata, as well as when you click "Edit Item"->Advanced Tab. Next, uncheck **Assign PIDS to new items** and create a new item, ensuring that no PID appears.
- Extract PID from Existing Fields: on the PID module **Settings** page, enter several fields that may contain PID values, such as _dcterms.identifier_,_dcterms.relation_, etc. go to an item edit page and put a "dummy" PID value such as ark:/99999/fk4kw6wp07 or 10.82157/7mzm-ee29 in to each of the entered fields, then test minting a PID from the _Advanced_ tab for each metadata field, to make sure that the dummy value you entered in the metadata field gets saved as the items PID value.
- Batch mint/extract/delete PIDs: from the admin interface _Items_ page, select the checkbox beside several items without PIDs, choose "Edit Selected" and press "Go". Near the bottom of the _Batch edit items_ screen, you should see a Persistent Identifiers row. Test the _Mint PIDs_, _Remove PIDs_ and _[no action]_ buttons in turn, ensuring that PIDs are minted or removed for the selected items. Also ensure that one or two of the items have PID values in an "Existing Field" value from above, and that these PIDs are properly extracted while other PIDs are newly minted.
- Importing from other sources: import a small collection from another Omeka S Instance or DSpace/Fedora repository, CSV import etc. using another module. When **Assign PIDs to all new items** is checked, ensure that all imported items have a PID assigned. Also see if you can put PID values in the relevant Existing Field within the source repository, BEFORE import, and ensure that those PIDs are assigned to the newly imported items after import.
- **For DataCite**: test that the DataCite Configuration page will not let you save without selecting a match for each Required Metadata field.
- Test PIDs resolve to item landing page:
   - **For EZID**: Append the ARK value to the EZID resolution server, like so: http://n2t.net/ + **ark:/99999/fk4kw6wp07**, or http://n2t.net/ark:/99999/fk4kw6wp07
   - **For DataCite**: Append the DOI value to the DataCite test server URI, like so: https://handle.stage.datacite.org/ + **10.82157/7mzm-ee29**, or https://handle.stage.datacite.org/10.82157/7mzm-ee29.
   - For each service, put the URL in a browser and ensure that it returns a page on your Omeka instance without any site-specific formatting, but which includes the item's title, metadata, any related media, the Sites the item belongs to and the PID itself.
- Test "tombstone" page after removal: For each service, Remove the PID in the Item Edit screen. Afterwards, attempt to navigate to the same URL link as above. For each service, you should instead be redirected to a page stating "The given identifier is not associated with any object" or similar.

Please let me know if you have questions or if there is a testing task/behavior I might be missing. Thank you!!

**Comment by katknow** [comment]
So, I configured the ARK settings but when I go in to edit an item, advanced, and click Mint PID I get [object, Object]:

![image](https://user-images.githubusercontent.com/84726696/158650051-dd372c61-c69b-458e-8356-c5154c01ec87.png)

I used NAAN & Shoulder Namespace, EZID Username and EZID Password listed above for testing

**Comment by matthewjmckinley** [comment]
That usually means a 500 internal server error--does anything appear in `logs/application.log` after you press the mint button?

**Comment by katknow** [comment]
@matthewjmckinley I'm not seeing anything

**Comment by matthewjmckinley** [comment]
Hmmm OK... what about in the web developer window? Not sure what browser you are on, but in Chrome if you right click the [object Object] element, select `inspect`, then click to the `console` tab in the window that pops up, it should show you a line with the error and a link to the `pid-edit.js` page or similar. Clicking that link should attempt to navigate to that page, and show a more detailed error message. It's a similar process to access the `console` window in most other browsers.

**Comment by katknow** [comment]
This is the error:

Laminas\ServiceManager\Exception\ServiceNotFoundException
Unable to resolve service "ezid" to a factory; are you certain you provided it during configuration?

Details:

Laminas\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "ezid" to a factory; are you certain you provided it during configuration? in /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-servicemanager/src/ServiceManager.php:688
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(764): Laminas\ServiceManager\ServiceManager->getFactory('ezid')
#1 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate('ezid')
#2 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(153): Laminas\ServiceManager\ServiceManager->get('ezid')
#3 /var/www/html/katknow/OmekaSTesting/modules/PersistentIdentifiers/src/PIDSelector/Manager.php(14): Laminas\ServiceManager\AbstractPluginManager->get('ezid', NULL)
#4 /var/www/html/katknow/OmekaSTesting/modules/PersistentIdentifiers/src/Controller/IndexController.php(121): PersistentIdentifiers\PIDSelector\Manager->get('ezid')
#5 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): PersistentIdentifiers\Controller\IndexController->pidEditAction()
#6 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#7 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#8 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(105): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#9 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#10 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#11 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#12 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#13 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#14 {main}

**Comment by matthewjmckinley** [comment]
On line 26 of `PersistentIdentifiers/config/module.config.php`, could you change:

`'ezid' => PersistentIdentifiers\Service\PIDSelector\EzidFactory::class,`

to 

`'ezid' => PersistentIdentifiers\Service\PIDSelector\EZIDFactory::class,` (capitalized)

And try minting again?

**Comment by katknow** [comment]
That seemed to do it, thanks!

**Comment by katknow** [comment]
I'd made it up to the bullet point for importing from elsewhere when I started getting this message when I hit the Mint PID button: "Could not mint PID, check credentials/settings." I was trying to import from my own library so I could have control over the PIDs when it started doing that, so I might've broken it somewhere in that process. I tried the steps from yesterday to find an error but nothing is coming up

![Screenshot 2022-03-17 104049](https://user-images.githubusercontent.com/84726696/158829975-26d842fa-44de-4d13-9053-f904aa75aad0.png)

**Comment by matthewjmckinley** [comment]
Whoops, sorry I missed this! When you say 'import from my own library', do you mean via CSV Import? Can you give me more information on what source you used for import, and if possible share some of the metadata/PID values you were loading in?

**Comment by katknow** [comment]
I tried to do a direct Omeka S Item Importer [from this site](http://dev.omeka.org/katknow/OmekaSTesting/s/test123/page/welcome) to itself, something I've done in other testing so I could have control over the items to play with fields that needed to be edited. Only [one item](http://dev.omeka.org/katknow/OmekaSTesting/s/test123/item/26942) had a PID, because I wanted to see if it worked before I added more. Upon further investigation, it appears the problem is now only for items that things existing already in the identifier field? So I guess the problem is the lack of option for the removing of the PID rather than the adding of a PID. I can add you as an admin for the site of you want to take a closer look at anything, and I'll keep clicking around since it's not acting in the way I initially thought it was.

**Comment by matthewjmckinley** [comment]
Sure, admin access would be helpful so I can try to pinpoint/replicate what is going on. My email is matthewjamesmckinley@gmail.com

**Comment by katknow** [comment]
Okay, I've added you. Pardon how messy my testing instance is, and all of the pictures of my dog I've used as test items.

**Comment by matthewjmckinley** [comment]
I love the Daphne photos :)

And I think I determined the issue: there was a stray whitespace at the end of the PID value in the dc:identifier field for that item. When I removed the space, it extracted/assigned the PID just fine.

I've put in a fix to trim the whitespace from extracted PID values, so please pull the latest code and try extracting a PID value from an existing field WITH the whitespace at beginning/end and make sure that it removes it and assigns the PID correctly.

**Comment by katknow** [comment]
So, I finally was able to get the export to work but even with the box checked it did not assign new PIDs to the ones that did not previously have them. However, it did import existing PIDs from the source. I did this via the Omeka S Item Importer, but was unable to try via CSV Import as when I installed the module in took down my whole site. 

(Side note - I'm working on my comprehensive exams this week but will be back to a more regular testing schedule next week!)

**Comment by matthewjmckinley** [comment]
I suspect the issue may be the fact that you are 'importing' items from the site to itself with the Omeka S Item Importer--I've been trying the same with my local instance and getting some strange results, even apart from PID generation. Hopefully importing from another Omeka S instance, or using another importer module such as CSV Import/DSpace/Fedora/etc. will yield better results.

**Comment by sharonmleon** [comment]
@katknow Just checking in on this. If this seems resolved, then we can move on documentation.

**Comment by sharonmleon** [comment]
@matthewjmckinley I think we probably need a little more helper text in the Settings view. I honestly was just clicking around with out reading the testing issue, and checked the Auto-assign box for EZID but didn't do any of the other configuration, which, of course, produced a big ugly error for the new Item creation. Maybe just in helper text on the PID Service line we could parenthetical (Input service credentials in configuration)?

Also, I wonder if my mistake is about the way that the left menu functions? When I select Persistent Identifiers from the Modules menu, the settings view loads and reorients the whole page to the top of the screen. At my current resolution, that means that I cannot see the sub-items on the module navigation (they are below the fold, so to speak). I wonder if that means that the configurations for the services shouldn't be in the Omeka S left navigation, but rather as a configuration option for the module that is available for installation, upgrade, etc. 

@jimsafley  @kimisgold Do you have thoughts on best practices here?

**Comment by sharonmleon** [comment]
Also, just checking to make sure that when Auto-assign PID has been selected in the setup, the individual user cannot uncheck that box. That's the behavior now, and I think it should be the desired behavior, but want to be sure.

**Comment by katknow** [comment]
@sharonmleon @matthewjmckinley sorry I had missed the reply to my last comment. It was still being finicky, but since the CSV Import kept breaking my instance I only tested importing from my own install. I can test from another instance if you have recommendations of ones with open APIs etc. At that point, the main issue I was having was the new items were not getting assigned PIDs with the box checked.

**Comment by sharonmleon** [comment]
@katknow I'll get some IDs on my stuff and then pass along the API

**Comment by katknow** [comment]
@sharonmleon sounds good, thank you!

**Comment by matthewjmckinley** [comment]
@sharonmleon that's a good catch; since credentials are required as soon as you load the EZID/DataCite Configuration screen, I hadn't tested auto-assign without any credentials at all. A tooltip would be an easy fix, but I do wonder if your idea of putting credentials in the configuration makes more sense. These are settings that wouldn't be changed very often or at all, and it would make the PID module navigation a lot cleaner. My only concern is it's possibly less modular and more unwieldy to have the configuration settings for all services on a single page/form, especially if we add more services. I don't know which route would be more or less intuitive for UX.

And yes, greying out the box for assign PID at the item-level was by design. I think an argument could be made either way. This is more of a pain for someone who wants to generate only one item without a PID for some reason, but makes it's impossible for someone like a student etc. to accidentally uncheck the box.

**Comment by sharonmleon** [comment]
I figured that was the case on the auto-assign, and that makes sense.

I'll be interested in what @jimsafley and @kimisgold say about the configuration location.

**Comment by katknow** [comment]
Finally was able to get CSV import to work and it does add the new PIDs as expected via that method when the box is checked for EZID, so I'm thinking some of my initial issues must've been from trying to import from my own instance. I'll do another round via CSV with the DataCite, hopefully with the same success.

**Comment by katknow** [comment]
@matthewjmckinley I think I must've messed something up when trying to get the CSV Import to work because I am getting the "Could not mint PID, check credentials/settings." message again when trying to create new PIDs for DataCite

**Comment by matthewjmckinley** [comment]
Remember that DataCite items must contain a value for every metadata field mapped in the 'DataCite required metadata' configuration, i.e. Title, Creators, Publisher, Publication Year and Resource Type General. 

Also, the "Resource Type General" value, in this case mapped to dcterms:format, must annoyingly conform EXACTLY to a controlled list that is buried in the DataCite metadata schema https://schema.datacite.org . In other words, "image/jpeg" won't work, "image" won't work, but "Image" will. I can make this clearer in the tooltip.

I tested this by generating a DataCite DOI for http://dev.omeka.org/katknow/OmekaSTesting/admin/item/26977 -- despite having all the required it gave a "Could not mint PID" until I changed the Format value from "image/jpeg" to "Image", then it worked.

**Comment by katknow** [comment]
Good to know, thanks! Didn't realize it was that specific re. the image example

**Comment by matthewjmckinley** [comment]
It is annoyingly exact. FWIW I guess I already put a link in the tooltip to the controlled vocab in the latest commit: https://github.com/omeka-s-modules/PersistentIdentifiers/commit/fe5ffee2c9c725667b7110717918ad63443eef1e

**Comment by katknow** [comment]
Just ran through everything with DataCite plus CSV this time and it seems all is working as anticipated

**Comment by sharonmleon** [comment]
That's great, @katknow. Once we get some clarity on the location of the configuration stuff, I'll ask you to get started on documentation.

**Comment by kimisgold** [comment]
I sat down and formed a couple thoughts. I agree with Sharon that there's a lot the user can easily miss during setup. My current suggestion is to condense the configuration tabs for EZID and Datacite into the main Settings tab, only appearing after one is selected via that first set of radio inputs. That way that initial setting isn't missed, and the user only concerns themselves with the pertinent settings.

![image](https://user-images.githubusercontent.com/606764/166526817-18601fc2-fa27-4b32-8e4f-cac49c877cd4.png)

On a smaller note, I think including a few more success messages upon submission would be helpful. I was particularly uncertain if a form submitted whenever I was working with passwords.

**Comment by matthewjmckinley** [comment]
Great suggestions! I'll get to work on this

**Comment by matthewjmckinley** [comment]
@katknow @sharonmleon the display changes above are in place & this is ready for final testing. Don't know if it needs the full test procedure again, I think just testing that the EZID / DataCite credentials work and that you can switch between them should be good.

**Comment by katknow** [comment]
Everything seemed to work for me after the changes, and it seems more user friendly now.
