### ISSUE TITLE
Documentation: Persistent Identifiers Module

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka-s-modules/PersistentIdentifiers#5]
This module is ready for documentation. Features and operation are pretty well covered in the [testing issue](https://github.com/omeka-s-modules/PersistentIdentifiers/issues/4), but please let me know if I can clarify or elaborate anywhere!

**Comment by katknow** [comment]
I will give this another proofread (especially to make sure it matches style guidelines), but [here's the first draft](https://github.com/katknow/Drafts/blob/a26b72e0bc36eebe21e9ae40a5f1edea0495b8f5/persistentidentifiers.md) if you'd like to take a look and suggest changes. Like you said, the testing feature covered it pretty well.

**Comment by matthewjmckinley** [comment]
This looks great from a technical standpoint. I have a few small suggestions for wording etc., but those can wait until after you take another pass. Overall it is spot on!

**Comment by katknow** [comment]
Here's an [updated draft](https://github.com/katknow/Drafts/blob/c2be13f38d279d7dc5797d58295b21371b9a72d8/persistentidentifiers.md) for the PID Module to better reflect style guidelines and simplify language. I'm happy to make any wording changes.

**Comment by matthewjmckinley** [comment]
"Note that this password does not save" might be unclear -- the password does save, it just can't be accessed and re-shown within the form field (Laminas form default, for added security). I would maybe change to "Note that for security reasons this password doesn't persist in the form, so if changes...".

Also for DataCite Required Metadata, the Resource Type General property must conform to a ResourceTypeGeneral controlled value exactly, i.e. "Text" is correct but "text" is not. This tripped me up for a while testing. It's mentioned in the drop-down within the form but maybe also mention it here and link to the [controlled vocab value list](https://support.datacite.org/docs/datacite-metadata-schema-v44-mandatory-properties#101-resourcetypegeneral).

Otherwise looks good to go, thanks!
