### ISSUE TITLE
Module entry in sidebar appears despite user roles

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/PersistentIdentifiers#6]
My audit of module behaviour shows this one appears in the sidebar even when a user role / site user role should not display it. 
In this test, a Researcher role who has no permissions on the displayed site is able to see this:

![showingup](https://user-images.githubusercontent.com/28012148/181099491-f0f9ea9a-94dd-43c8-a592-b491ad1c2510.PNG)

Persistent Identifiers pulls up the service form (didn't test it all the way through).

**Comment by zerocrates** [comment]
Have you looked at this at all, Matthew?

**Comment by matthewjmckinley** [comment]
I did see this and could have sworn I fixed it at the time but apparently not. Regardless, should be fixed here: https://github.com/omeka-s-modules/PersistentIdentifiers/commit/d832048f74ce393768a1e78da607244c4acfcc33
