### ISSUE TITLE
PHP 8.2: deprecation warning

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/PersistentIdentifiers#8]
> Deprecated: Creation of dynamic property PersistentIdentifiers\Controller\IndexController::$api is deprecated in /var/www/html/omeka-s/modules/PersistentIdentifiers/src/Controller/IndexController.php on line 30

This just means you haven't declared the `$api` property in your IndexController class.

**Comment by matthewjmckinley** [comment]
Fixed by https://github.com/omeka-s-modules/PersistentIdentifiers/commit/3714d765e6899a12c903def9e6f7ad0ceb986dfa
