### ISSUE TITLE
Module breaks the Advanced tab on resources

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/PersistentIdentifiers#9]
This module adds itself to the Advanced tab in an improper way that results in two Advanced tabs being rendered, one always hidden.

This could be either more or less harmless, or make the visible Advanced tab nonfunctional, depending on which copy of the ID the browser decides to show when opening that tab.

To add to advanced, this should just be listening to the view.edit.form.advanced event and adding its form element, not rendering out an advanced tab with the form's before event.

**Comment by matthewjmckinley** [comment]
Fixed in https://github.com/omeka-s-modules/PersistentIdentifiers/commit/a2515f41289b5ed6d390a597b890ea7e60654418
